
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: service-b-deployment-5b99db849d-6z98k-11001
  namespace: custom
spec:
  hosts:
  - service-b-deployment-5b99db849d-6z98k
  addresses:
  - 172.31.233.217
  ports:
  - number: 11001
    name: http
    protocol: HTTP
  resolution: STATIC
  location: MESH_INTERNAL
  endpoints:
  - address: 172.31.233.217
    ports:
      http: 11001
