
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: service-b-deployment-5b99db849d-t9qk7-11001
  namespace: custom
spec:
  hosts:
  - service-b-deployment-5b99db849d-t9qk7
  addresses:
  - 172.24.182.14
  ports:
  - number: 11001
    name: http
    protocol: HTTP
  resolution: STATIC
  location: MESH_INTERNAL
  endpoints:
  - address: 172.24.182.14
    ports:
      http: 11001
