apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: service-e-filter
  namespace: paper2
spec:
  workloadSelector:
    labels:
      app: service-e  # 'app: service-c' 라벨을 가진 모든 파드의 Envoy에 적용
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_INBOUND  # 또는 SIDECAR_INBOUND, GATEWAY 등
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
    patch:
      operation: MERGE
      value:
        name: envoy.filters.http.lua
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
          inline_code: |
            function envoy_on_request(request_handle)
              request_handle:logInfo("Lua script executed")  
              local source_ip = request_handle:headers():get("x-forwarded-for")
              local destination_ip = request_handle:headers():get(":authority")
              request_handle:logInfo("Source IP: " .. (source_ip or "nil") .. ", Destination IP: " .. (destination_ip or "nil"))
            end