apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: frontend-pair-worker1-9656c64c6-lz72x-12001
  namespace: pair
spec:
  hosts:
    - frontend-pair-worker1-9656c64c6-lz72x
  addresses:
    - 172.20.235.155
  ports:
    - number: 12001
      name: http
      protocol: HTTP
  resolution: STATIC
  location: MESH_INTERNAL
  endpoints:
    - address: 172.20.235.155
      ports:
        http: 12001
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: frontend-pair-worker2-8569d4669f-5w8mb-12001
  namespace: pair
spec:
  hosts:
    - frontend-pair-worker2-8569d4669f-5w8mb
  addresses:
    - 172.31.111.111
  ports:
    - number: 12001
      name: http
      protocol: HTTP
  resolution: STATIC
  location: MESH_INTERNAL
  endpoints:
    - address: 172.31.111.111
      ports:
        http: 12001
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: frontend-pair-worker3-655c586b5d-gv96n-12001
  namespace: pair
spec:
  hosts:
    - frontend-pair-worker3-655c586b5d-gv96n
  addresses:
    - 172.24.182.18
  ports:
    - number: 12001
      name: http
      protocol: HTTP
  resolution: STATIC
  location: MESH_INTERNAL
  endpoints:
    - address: 172.24.182.18
      ports:
        http: 12001
