apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: load-generator-worker1-759888dfc9-c7jdp-12000
  namespace: pair
spec:
  hosts:
  - load-generator-worker1-759888dfc9-c7jdp
  addresses:
  - 172.20.235.147
  ports:
  - number: 12000
    name: http
    protocol: HTTP
  resolution: STATIC
  location: MESH_INTERNAL
  endpoints:
  - address: 172.20.235.147
    ports:
      http: 12000
