
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: service-e-deployment-5b7f57b8c-xpqwk-11004
  namespace: custom
spec:
  hosts:
  - service-e-deployment-5b7f57b8c-xpqwk
  addresses:
  - 172.22.33.12
  ports:
  - number: 11004
    name: http
    protocol: HTTP
  resolution: STATIC
  location: MESH_INTERNAL
  endpoints:
  - address: 172.22.33.12
    ports:
      http: 11004
