apiVersion: apps/v1
kind: Deployment
metadata:
  name: graph-generator-deployment
  namespace: hk-sched
  labels:
    app: graph-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graph-generator
  template:
    metadata:
      labels:
        app: graph-generator
    spec:
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: graph-generator
        image: hokunpark/graph-generator:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 13001
        command: ["/graph-generator"]