apiVersion: v1
kind: Service
metadata:
  name: graph-generator-service
  namespace: hk-sched
spec:
  selector:
    app: graph-generator
  ports:
    - protocol: TCP
      port: 13001
      targetPort: 13001
  type: ClusterIP

