apiVersion: v1
kind: Service
metadata:
  name: traffic-monitor-service
  namespace: hk-sched
spec:
  selector:
    app: traffic-monitor
  ports:
    - protocol: TCP
      port: 13000
      targetPort: 13000
  type: ClusterIP

