
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: service-c-deployment-57cd84fbfc-84vkh-11002
  namespace: custom
spec:
  hosts:
  - "service-c-deployment-57cd84fbfc-84vkh"
  addresses:
  - 172.20.235.145
  ports:
  - number: 11002
    name: http
    protocol: HTTP
  resolution: STATIC
  location: MESH_INTERNAL
  endpoints:
  - address: 172.20.235.145
    ports:
      http: 11002
