
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: service-c-deployment-57cd84fbfc-jcg5j-11002
  namespace: custom
spec:
  hosts:
  - "service-c-deployment-57cd84fbfc-jcg5j"
  addresses:
  - 172.31.233.209
  ports:
  - number: 11002
    name: http
    protocol: HTTP
  resolution: STATIC
  location: MESH_INTERNAL
  endpoints:
  - address: 172.31.233.209
    ports:
      http: 11002
