# Service 생성
apiVersion: v1
kind: Service
metadata:
  name: node-metric-collector
  namespace: hk-sched
spec:
  selector:
    app: node-metric-collector
  ports:
    - name: http
      port: 21002
      targetPort: 21002
  type: ClusterIP

---
# ServiceAccount 생성
apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-metric-collector-sa
  namespace: hk-sched
  labels:
    app: node-metric-collector

---
# ClusterRole 생성 - 모든 네임스페이스의 서비스 및 파드 리소스에 접근 가능
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-metric-collector-role
  labels:
    app: node-metric-collector
rules:
  - apiGroups: [""]
    resources: ["services", "pods"]
    verbs: ["get", "list", "watch"]

---
# ClusterRoleBinding 생성 - ServiceAccount에 ClusterRole 권한 부여
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: node-metric-collector-binding
  labels:
    app: node-metric-collector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: node-metric-collector-role
subjects:
  - kind: ServiceAccount
    name: node-metric-collector-sa
    namespace: hk-sched

---

