apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: load-generator-filter
  namespace: pair
spec:
  workloadSelector:
    labels:
      app: load-generator
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_OUTBOUND
        listener:
          filterChain:
            filter:
              name: envoy.filters.network.http_connection_manager
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.lua
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
            inline_code: |-
              local pod_ip = nil
              local counters = {}
              local status_value = 0
              local required_vars = 1

              for i = 1, required_vars do
                if not counters[i] then
                  counters[i] = 0
                end
              end

              function envoy_on_request(request_handle)
                if not pod_ip then
                  local handle = io.popen("hostname -i")
                  pod_ip = handle:read("*a"):match("^%s*(.-)%s*$")
                  handle:close()
                end

                local destination = request_handle:headers():get(":authority")
                local domain = destination:match("^([^:]+)")

                if domain == "frontend-pair" and status_value == 0 then
                  local new_destination = nil
                  if pod_ip == "172.20.235.147" then
                    counters[1] = counters[1] + 1
                    local sequence = { "frontend-pair-worker1-9656c64c6-lz72x", "frontend-pair-worker2-8569d4669f-5w8mb", "frontend-pair-worker3-655c586b5d-gv96n", "frontend-pair-worker1-9656c64c6-lz72x", "frontend-pair-worker2-8569d4669f-5w8mb", "frontend-pair-worker1-9656c64c6-lz72x", "frontend-pair-worker2-8569d4669f-5w8mb", "frontend-pair-worker3-655c586b5d-gv96n", "frontend-pair-worker1-9656c64c6-lz72x", "frontend-pair-worker2-8569d4669f-5w8mb", "frontend-pair-worker3-655c586b5d-gv96n", "frontend-pair-worker1-9656c64c6-lz72x", "frontend-pair-worker2-8569d4669f-5w8mb", "frontend-pair-worker1-9656c64c6-lz72x", "frontend-pair-worker2-8569d4669f-5w8mb", "frontend-pair-worker3-655c586b5d-gv96n", "frontend-pair-worker1-9656c64c6-lz72x", "frontend-pair-worker2-8569d4669f-5w8mb", "frontend-pair-worker1-9656c64c6-lz72x", "frontend-pair-worker2-8569d4669f-5w8mb", "frontend-pair-worker3-655c586b5d-gv96n", "frontend-pair-worker1-9656c64c6-lz72x", "frontend-pair-worker2-8569d4669f-5w8mb", "frontend-pair-worker1-9656c64c6-lz72x", "frontend-pair-worker2-8569d4669f-5w8mb", "frontend-pair-worker3-655c586b5d-gv96n", "frontend-pair-worker1-9656c64c6-lz72x", "frontend-pair-worker2-8569d4669f-5w8mb", "frontend-pair-worker3-655c586b5d-gv96n", "frontend-pair-worker1-9656c64c6-lz72x", "frontend-pair-worker2-8569d4669f-5w8mb", "frontend-pair-worker1-9656c64c6-lz72x", "frontend-pair-worker2-8569d4669f-5w8mb", "frontend-pair-worker3-655c586b5d-gv96n", "frontend-pair-worker1-9656c64c6-lz72x", "frontend-pair-worker2-8569d4669f-5w8mb", "frontend-pair-worker1-9656c64c6-lz72x", "frontend-pair-worker2-8569d4669f-5w8mb", "frontend-pair-worker3-655c586b5d-gv96n", "frontend-pair-worker1-9656c64c6-lz72x", "frontend-pair-worker2-8569d4669f-5w8mb", "frontend-pair-worker1-9656c64c6-lz72x", "frontend-pair-worker2-8569d4669f-5w8mb", "frontend-pair-worker3-655c586b5d-gv96n", "frontend-pair-worker1-9656c64c6-lz72x", "frontend-pair-worker2-8569d4669f-5w8mb", "frontend-pair-worker3-655c586b5d-gv96n", "frontend-pair-worker1-9656c64c6-lz72x", "frontend-pair-worker2-8569d4669f-5w8mb", "frontend-pair-worker1-9656c64c6-lz72x", "frontend-pair-worker2-8569d4669f-5w8mb", "frontend-pair-worker3-655c586b5d-gv96n", "frontend-pair-worker1-9656c64c6-lz72x", "frontend-pair-worker2-8569d4669f-5w8mb", "frontend-pair-worker1-9656c64c6-lz72x", "frontend-pair-worker2-8569d4669f-5w8mb", "frontend-pair-worker3-655c586b5d-gv96n", "frontend-pair-worker1-9656c64c6-lz72x", "frontend-pair-worker2-8569d4669f-5w8mb", "frontend-pair-worker1-9656c64c6-lz72x", "frontend-pair-worker2-8569d4669f-5w8mb", "frontend-pair-worker3-655c586b5d-gv96n", "frontend-pair-worker1-9656c64c6-lz72x", "frontend-pair-worker2-8569d4669f-5w8mb", "frontend-pair-worker1-9656c64c6-lz72x", "frontend-pair-worker2-8569d4669f-5w8mb", "frontend-pair-worker3-655c586b5d-gv96n", "frontend-pair-worker1-9656c64c6-lz72x", "frontend-pair-worker2-8569d4669f-5w8mb", "frontend-pair-worker3-655c586b5d-gv96n", "frontend-pair-worker1-9656c64c6-lz72x", "frontend-pair-worker2-8569d4669f-5w8mb", "frontend-pair-worker1-9656c64c6-lz72x", "frontend-pair-worker2-8569d4669f-5w8mb", "frontend-pair-worker3-655c586b5d-gv96n", "frontend-pair-worker1-9656c64c6-lz72x", "frontend-pair-worker2-8569d4669f-5w8mb", "frontend-pair-worker1-9656c64c6-lz72x", "frontend-pair-worker2-8569d4669f-5w8mb", "frontend-pair-worker3-655c586b5d-gv96n", "frontend-pair-worker1-9656c64c6-lz72x", "frontend-pair-worker2-8569d4669f-5w8mb", "frontend-pair-worker1-9656c64c6-lz72x", "frontend-pair-worker2-8569d4669f-5w8mb", "frontend-pair-worker3-655c586b5d-gv96n", "frontend-pair-worker1-9656c64c6-lz72x", "frontend-pair-worker2-8569d4669f-5w8mb", "frontend-pair-worker3-655c586b5d-gv96n", "frontend-pair-worker1-9656c64c6-lz72x", "frontend-pair-worker2-8569d4669f-5w8mb", "frontend-pair-worker1-9656c64c6-lz72x", "frontend-pair-worker2-8569d4669f-5w8mb", "frontend-pair-worker3-655c586b5d-gv96n", "frontend-pair-worker1-9656c64c6-lz72x", "frontend-pair-worker2-8569d4669f-5w8mb", "frontend-pair-worker1-9656c64c6-lz72x", "frontend-pair-worker2-8569d4669f-5w8mb", "frontend-pair-worker3-655c586b5d-gv96n", "frontend-pair-worker1-9656c64c6-lz72x", "frontend-pair-worker2-8569d4669f-5w8mb" }
                    if counters[1] > #sequence then
                      counters[1] = 1
                    end
                    new_destination = sequence[counters[1]]
                  end
                  if new_destination then
                    local new_destination_with_port = new_destination .. destination:match("(:.*)$")
                    request_handle:headers():replace(":authority", new_destination_with_port)
                    request_handle:headers():replace("Host", new_destination_with_port)
                  end
                end
              end

              function envoy_on_response(response_handle)
                local status_code = tonumber(response_handle:headers():get(":status"))

                if status_code >= 400 then
                  status_value = 1
                end
              end
