
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: service-d-deployment-79b86d59bd-7f7tn-11003
  namespace: custom
spec:
  hosts:
  - service-d-deployment-79b86d59bd-7f7tn
  addresses:
  - 172.22.33.13
  ports:
  - number: 11003
    name: http
    protocol: HTTP
  resolution: STATIC
  location: MESH_INTERNAL
  endpoints:
  - address: 172.22.33.13
    ports:
      http: 11003
