
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: service-c-deployment-57cd84fbfc-ms7sb-11002
  namespace: custom
spec:
  hosts:
  - service-c-deployment-57cd84fbfc-ms7sb
  addresses:
  - 172.20.235.150
  ports:
  - number: 11002
    name: http
    protocol: HTTP
  resolution: STATIC
  location: MESH_INTERNAL
  endpoints:
  - address: 172.20.235.150
    ports:
      http: 11002
