
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: service-c-deployment-57cd84fbfc-26ghs-11002
  namespace: custom
spec:
  hosts:
  - service-c-deployment-57cd84fbfc-26ghs
  addresses:
  - 172.31.233.214
  ports:
  - number: 11002
    name: http
    protocol: HTTP
  resolution: STATIC
  location: MESH_INTERNAL
  endpoints:
  - address: 172.31.233.214
    ports:
      http: 11002
