
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: service-b-deployment-5b99db849d-f4mgj-11001
  namespace: custom
spec:
  hosts:
  - service-b-deployment-5b99db849d-f4mgj
  addresses:
  - 172.24.182.11
  ports:
  - number: 11001
    name: http
    protocol: HTTP
  resolution: STATIC
  location: MESH_INTERNAL
  endpoints:
  - address: 172.24.182.11
    ports:
      http: 11001
