apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: service-b-filter
  namespace: custom
spec:
  workloadSelector:
    labels:
      app: service-b
      namespace: custom

  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_OUTBOUND
        listener:
          filterChain:
            filter:
              name: envoy.filters.network.http_connection_manager

      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.lua
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
            inlineCode: |
              local pod_ip = nil

              function envoy_on_request(request_handle)
                -- Pod IP를 한 번만 가져오기
                if not pod_ip then
                  local handle = io.popen("hostname -i")
                  pod_ip = handle:read("*a"):match("^%s*(.-)%s*$")
                  handle:close()
                end
                request_handle:logWarn("Pod IP: " .. tostring(pod_ip))
                -- 요청에서 목적지 호스트(:authority) 헤더 추출
                local destination = request_handle:headers():get(":authority")
                local domain = destination:match("^([^:]+)")

                if domain == "service-c" then
                  local new_destination = nil
                  local rand = math.random(0, 100)
                  if pod_ip == "172.20.235.152" then
                    if rand <= 0 then
                          new_destination = "service-c-deployment-57cd84fbfc-ms7sb"
                    elseif rand <= 100 then
                          new_destination = "service-c-deployment-57cd84fbfc-26ghs"
                    end
                  elseif pod_ip == "172.22.33.11" then
                    if rand <= 0 then
                          new_destination = "service-c-deployment-57cd84fbfc-ms7sb"
                    elseif rand <= 100 then
                          new_destination = "service-c-deployment-57cd84fbfc-26ghs"
                    end
                  elseif pod_ip == "172.24.182.14" then
                    if rand <= 0 then
                          new_destination = "service-c-deployment-57cd84fbfc-ms7sb"
                    elseif rand <= 100 then
                          new_destination = "service-c-deployment-57cd84fbfc-26ghs"
                    end
                  elseif pod_ip == "172.31.233.217" then
                    if rand <= 0 then
                          new_destination = "service-c-deployment-57cd84fbfc-ms7sb"
                    elseif rand <= 100 then
                          new_destination = "service-c-deployment-57cd84fbfc-26ghs"
                    end
                  end
                  if new_destination then
                    local new_destination = new_destination .. destination:match("(:.*)$")
                    request_handle:headers():replace(":authority", new_destination)
                    request_handle:headers():replace("Host", new_destination)
                  end
                end
              end
