
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: service-a-deployment-696cb64c9-5446p-11000
  namespace: custom
spec:
  hosts:
  - service-a-deployment-696cb64c9-5446p
  addresses:
  - 172.20.235.144
  ports:
  - number: 11000
    name: http
    protocol: HTTP
  resolution: STATIC
  location: MESH_INTERNAL
  endpoints:
  - address: 172.20.235.144
    ports:
      http: 11000
