
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: service-a-deployment-696cb64c9-k5jch-11000
  namespace: custom
spec:
  hosts:
  - service-a-deployment-696cb64c9-k5jch
  addresses:
  - 172.24.182.10
  ports:
  - number: 11000
    name: http
    protocol: HTTP
  resolution: STATIC
  location: MESH_INTERNAL
  endpoints:
  - address: 172.24.182.10
    ports:
      http: 11000
