
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: service-a-deployment-696cb64c9-vc94n-11000
  namespace: custom
spec:
  hosts:
  - service-a-deployment-696cb64c9-vc94n
  addresses:
  - 172.31.233.215
  ports:
  - number: 11000
    name: http
    protocol: HTTP
  resolution: STATIC
  location: MESH_INTERNAL
  endpoints:
  - address: 172.31.233.215
    ports:
      http: 11000
