# ClusterRole 정의
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: custom-autoscaler-clusterrole
rules:
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources:
      [
        "deployments",
        "replicasets",
        "statefulsets",
        "deployments/scale",
        "statefulsets/scale",
      ]
    verbs: ["get", "list", "watch", "update", "patch"]

---
# ClusterRoleBinding 정의
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: custom-autoscaler-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: custom-autoscaler # 서비스 계정 이름
    namespace: hk-sched # 네임스페이스 설정
roleRef:
  kind: ClusterRole
  name: custom-autoscaler-clusterrole
  apiGroup: rbac.authorization.k8s.io

---
# ServiceAccount 정의
apiVersion: v1
kind: ServiceAccount
metadata:
  name: custom-autoscaler
  namespace: hk-sched
