apiVersion: v1
kind: Service
metadata:
  name: hpa-autoscaling-metrics-service
  namespace: hk-sched
spec:
  selector:
    app: hpa-autoscaling-metrics
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer # 클라우드 환경에서 외부 접근 가능하도록 설정
